REM Build Bat File
REM Precheck the Resource 
"C:\Program Files\MRE_SDK\tools\ResEditor\CmdShell.exe" save  "D:\MyGitHub\base64_mre\base64_mre.vcproj"
REM Copmile c file 
"C:\Program Files (x86)\CodeSourcery\Sourcery_CodeBench_Lite_for_ARM_EABI\Bin\arm-none-eabi-gcc" -c -fpic -g -mcpu=arm7tdmi-s -fvisibility=hidden -mthumb -mlittle-endian -O2 -D__MRE_COMPILER_GCC__ -fno-exceptions -fno-non-call-exceptions -o "D:\MyGitHub\base64_mre\arm\gccmain.o" -c "C:\Program Files\MRE_SDK\lib\MRE30\src\gccmain.c"      -D _MINIGUI_LIB_ -D _USE_MINIGUIENTRY -D _NOUNIX_ -D _FOR_WNC -D __MRE_SDK__ -D   __MRE_VENUS_NORMAL__  -D  __MMI_MAINLCD_240X320__ -I "C:\Program Files\MRE_SDK\include" -I "C:\Program Files\MRE_SDK\include\service" -I "D:\MyGitHub\base64_mre\include" -I "D:\MyGitHub\base64_mre\include\service" -I "D:\MyGitHub\base64_mre\include\component" -I "D:\MyGitHub\base64_mre\ResID" -I "D:\MyGitHub\base64_mre\src\app\widget" -I "D:\MyGitHub\base64_mre\src\app\launcher" -I "D:\MyGitHub\base64_mre\src\app\wallpaper" -I "D:\MyGitHub\base64_mre\src\app\screen_lock" -I "D:\MyGitHub\base64_mre\include\service" -I "D:\MyGitHub\base64_mre\include\component" -I "D:\MyGitHub\base64_mre\include\service" -I "D:\MyGitHub\base64_mre\src\framework" -I "D:\MyGitHub\base64_mre\src\framework\ui_core\base" -I "D:\MyGitHub\base64_mre\src\framework\ui_core\mvc" -I "D:\MyGitHub\base64_mre\src\framework\ui_core\pme" -I "D:\MyGitHub\base64_mre\src\framework\mmi_core" -I "D:\MyGitHub\base64_mre\src\ui_engine\vrt\interface" -I "D:\MyGitHub\base64_mre\src\component" -I "D:\MyGitHub\base64_mre\src\ui_engine\framework\xml" -I "D:\MyGitHub\base64_mre"
REM Copmile c file 
"C:\Program Files (x86)\CodeSourcery\Sourcery_CodeBench_Lite_for_ARM_EABI\Bin\arm-none-eabi-gcc" -c -fpic -g -mcpu=arm7tdmi-s -fvisibility=hidden -mthumb -mlittle-endian -O2 -D__MRE_COMPILER_GCC__ -fno-exceptions -fno-non-call-exceptions -o "D:\MyGitHub\base64_mre\arm\base64_mre.o" -c "d:\MyGitHub\base64_mre\base64_mre.c"      -D _MINIGUI_LIB_ -D _USE_MINIGUIENTRY -D _NOUNIX_ -D _FOR_WNC -D __MRE_SDK__ -D   __MRE_VENUS_NORMAL__  -D  __MMI_MAINLCD_240X320__ -I "C:\Program Files\MRE_SDK\include" -I "C:\Program Files\MRE_SDK\include\service" -I "D:\MyGitHub\base64_mre\include" -I "D:\MyGitHub\base64_mre\include\service" -I "D:\MyGitHub\base64_mre\include\component" -I "D:\MyGitHub\base64_mre\ResID" -I "D:\MyGitHub\base64_mre\src\app\widget" -I "D:\MyGitHub\base64_mre\src\app\launcher" -I "D:\MyGitHub\base64_mre\src\app\wallpaper" -I "D:\MyGitHub\base64_mre\src\app\screen_lock" -I "D:\MyGitHub\base64_mre\include\service" -I "D:\MyGitHub\base64_mre\include\component" -I "D:\MyGitHub\base64_mre\include\service" -I "D:\MyGitHub\base64_mre\src\framework" -I "D:\MyGitHub\base64_mre\src\framework\ui_core\base" -I "D:\MyGitHub\base64_mre\src\framework\ui_core\mvc" -I "D:\MyGitHub\base64_mre\src\framework\ui_core\pme" -I "D:\MyGitHub\base64_mre\src\framework\mmi_core" -I "D:\MyGitHub\base64_mre\src\ui_engine\vrt\interface" -I "D:\MyGitHub\base64_mre\src\component" -I "D:\MyGitHub\base64_mre\src\ui_engine\framework\xml" -I "D:\MyGitHub\base64_mre"
REM Link app 
"C:\Program Files (x86)\CodeSourcery\Sourcery_CodeBench_Lite_for_ARM_EABI\Bin\arm-none-eabi-gcc" -o "D:\MyGitHub\base64_mre\base64_mre.axf"  "D:\MyGitHub\base64_mre\arm\gccmain.o"  "D:\MyGitHub\base64_mre\arm\base64_mre.o" -fpic -msvr4-struct-return -pie  -T "C:\Program Files\MRE_SDK\lib\MRE30\armgcc\scat.ld" -l:"C:\Program Files\MRE_SDK\lib\MRE30\armgcc\percommon.a" -l:"C:\Program Files\MRE_SDK\lib\MRE30\armgcc\perfile.a" -l:"C:\Program Files\MRE_SDK\lib\MRE30\armgcc\persysstorage.a" -l:"C:\Program Files\MRE_SDK\lib\MRE30\armgcc\persysfile.a"
REM Pack resource to app 
"C:\Program Files\MRE_SDK\tools\ResEditor\CmdShell.exe" pack -silent -resolution 240x320 -o "D:\MyGitHub\base64_mre\base64_mre.pkd" -e AXF "D:\MyGitHub\base64_mre\base64_mre.vcproj" "D:\MyGitHub\base64_mre\base64_mre.axf"
REM Add tag infromation 
"C:\Program Files\MRE_SDK\tools\PackDigist.exe" "D:\MyGitHub\base64_mre\base64_mre.vcproj" "base64_mre" "0.1.0" "RDZDX" "1500" "NotSupportBg" "Not Support rotate" "base64_mre" "base64_mre" "base64_mre" "1234567890" "content" " File SysStorage SysFile" "vxp" "GCC" "PKD" "UnCompress" "NoVPI" "Adaptable" "15728960" "UnSysMemAble" "
    " "-1" "UNPUSH" "-1" ""  "UnAutoStart"  "UnTransferImg" "NoIdleShortcut"  D:\MyGitHub\base64_mre\arm D:\MyGitHub\base64_mre\build.log

